name: Daily Stock Scan

on:
  schedule:
    - cron: "0 3 * * *"
    - cron: "30 15 * * *"
  workflow_dispatch:   # ✅ allows manual run from UI

jobs:
  run-stock-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas

      - name: Run script
        run: python trading.py
